### ISSUE TITLE
Still not working by my friend 

### ISSUE THREAD

**Issue by Zeralun** [TcNobo/TcNo-Acc-Switcher#141]
my firend have still problems, it seems  that the program can not close anny aplications 

https://imgur.com/a/l2x6YKe

here some screenshots ^^

thank you for the program, the league problem is gone ^^

**Comment by TcNobo** [comment]
For now run the account switcher  as admin, this should fix the problem. I'll look into it further asap

**Comment by Zeralun** [comment]
alleady tryd that ^^"

still not working 
no worrys take ur time

**Comment by TcNobo** [comment]
In the account switcher > Steam > Settings, make sure this is checked and that should help then :)
![image](https://user-images.githubusercontent.com/10319195/151759098-c41b470c-aef2-47ac-8ab2-54a575946e78.png)

**Comment by Zeralun** [comment]
Perfect ^^ 
that works Many thanks ur the best !!!!
